package com.alpsfly.aeroglide.core.data.util


import com.alpsfly.aeroglide.core.model.database.Location
import java.text.DecimalFormat
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlin.math.absoluteValue
import kotlin.math.round

// https://xp-soaring.github.io/igc_file_format/igc_format_2008.html#link_4.1

class Igc(
    private val trackLog: List<Location>,
    private val departureDate: Long,
    private val pilot: String,
    private val gliderType: String,
    private val gliderId: String
) {
    private val headerList = StringBuilder()
    private val recordList = StringBuilder()
    private val accuracy = trackLog.map { item -> item.horizontalAccuracy }.average().toInt()

    // B1602455107126N00149300WA002880042919509020
    // B1602505107134N00149283WA002900043221009015
    // B1602555107140N00149221WA002900043020009012
    // F1603000609123624221821
    // B1603005107150N00149202WA002910043225608009
    // HHMMSSDDMMmmmHDDDMMmmmHFPPPPPGGGGG
    fun buildIgc(): String {
        buildHeader()
        trackLog.forEach { record ->
            val time = toTimeStr(record.timestamp)
            val lat = toLatStr2(record.latitude.toDouble())
            val lon = toLonStr2(record.longitude.toDouble())
            val fix = "A" // todo: store fix in database
            val presAlt = toAltStr(record.altitude)
            val gnssAlt = toAltStr(record.altitude)
            recordList.append("B$time$lat$lon$fix$presAlt$gnssAlt\n")
        }
        addSecurityRecord()
        return headerList.toString() + recordList.toString()
    }

    // AXXXABC FLIGHT:1
    // HFFXA035
    // HFDTE160701
    // HFPLTPILOTINCHARGE: Bloggs Bill D
    // HFCM2CREW2: Smith-Barry John A
    // HFGTYGLIDERTYPE: Schleicher ASH-25
    // HFGIDGLIDERID: ABCD-1234
    // HFDTM100GPSDATUM: WGS-1984
    // HFRFWFIRMWAREVERSION:6.4
    // HFRHWHARDWAREVERSION:3.0
    // HFFTYFRTYPE: Manufacturer, Model
    // HFGPSMarconiCanada: Superstar,12ch, max10000m
    // HFPRSPRESSALTSENSOR: Sensyn, XYZ1111, max11000m CR LF
    // HFCIDCOMPETITIONID: XYZ-78910
    // HFCCLCOMPETITIONCLASS:15m Motor Glider
    private fun buildHeader() {
        headerList.append("A" + "XXX" + " " + "https://alpsfly.com\n")
        headerList.append("HFFXA$accuracy\n")
        headerList.append("HFDTE${toDateStr(departureDate)}\n")
        headerList.append("HFPLTPILOTINCHARGE: ${pilot}\n")
        headerList.append("HFCM2CREW2: \n")
        headerList.append("HFGTYGLIDERTYPE: ${gliderType}\n")
        headerList.append("HFGIDGLIDERID: ${gliderId}\n")
        headerList.append("HFDTM100GPSDATUM: WGS-1984\n")
        headerList.append("HFRFWFIRMWAREVERSION: 1.0\n")
        headerList.append("HFRHWHARDWAREVERSION: 1.0\n")
        headerList.append("HFFTYFRTYPE: https://alpsfly.com\n")
        headerList.append("HFGPS: Android Location Sensor\n")
        headerList.append("HFPRSPRESSALTSENSOR: Android Pressure Sensor\n")
        headerList.append("HFCIDCOMPETITIONID: NONE\n")
        headerList.append("HFCCLCOMPETITIONCLASS: NONE\n")
    }

    private fun addSecurityRecord() {
        recordList.append("LXXX Generated by alpsfly.com\n")
        recordList.append("GAlpsflySecurityRecordGuaranteedToFailVALIChecks")
    }

    private fun toDateStr(timestamp: Long): String = LocalDateTime
        .ofInstant(Instant.ofEpochMilli(timestamp), ZoneId.systemDefault())
        .format(DateTimeFormatter.ofPattern("ddMMYY"))

    private fun toTimeStr(timestamp: Long): String = LocalDateTime
        .ofInstant(Instant.ofEpochMilli(timestamp), ZoneId.systemDefault())
        .format(DateTimeFormatter.ofPattern("HHmmss"))

    private fun toLatStr2(latitude: Double): String {
        val lat = latitude.absoluteValue
        val deg = lat.toInt()
        val degrees = DecimalFormat("00").format(deg)
        val min = round((lat - deg) * 60000)
        val minutes = DecimalFormat("00000").format(min.toInt())

        return when (latitude) {
            in (0f..90f) -> {
                degrees + minutes + "N"
            }

            in (-90f..0f) -> {
                degrees + minutes + "S"
            }

            else -> {
                "invalid"
            }
        }
    }

    // DDDMMmmmE/W
    private fun toLonStr2(longitude: Double): String {
        val lon = longitude.absoluteValue
        val deg = lon.toInt()
        val degrees = DecimalFormat("000").format(deg)

        val min = round((lon - deg) * 60000)
        val minutes = DecimalFormat("00000").format(min.toInt())

        return when (longitude) {
            in 0f..180f -> {
                degrees + minutes + "E"
            }

            in -180f..0f -> {
                degrees + minutes + "W"
            }

            else -> {
                "invalid"
            }
        }
    }

    private fun toAltStr(altitude: Float): String = DecimalFormat("00000").format(altitude.toInt())
}