graph TD;
    subgraph UI Layer
        A[ViewModel]
    end

    subgraph Domain Layer
        B(RecordingController)
        C(RecordActivityUseCase)
        D(CalibrationUseCase)
    end

    subgraph Data Layer
        E[SensorRepository]
        F[AppRepository]
        G[DataRepository]
    end

    subgraph Service Layer
        H[LocationService]
        I[ServiceStarter]
    end

    A --> B
    B --> C      
    B --> D     
    B --> E     
    B --> I     

    C --> E     
    C --> G    

    I --> H    

   
    B --> A_STATE(Sets State for ViewModel)
    style A_STATE fill:#f9f,stroke:#333,stroke-width:2px;

    B --> F     
    D --> F     

    %% This is the core logical problem: The Controller is both above and beside the UseCases.
    linkStyle 1 stroke:red,stroke-width:3px;
    linkStyle 2 stroke:red,stroke-width:3px;
    linkStyle 3 stroke:red,stroke-width:3px;
    linkStyle 4 stroke:red,stroke-width:3px;
